# Настройки Telegram бота
telegram:
  bot-token: "8263486505:AAHs0FDTQJrNRoMd1loLaNASWrp4SfKEuRc"
  chat-id: "-1002935953089"
  question-chat-id: "-1002935953089" # ID для вопросительного чата (пока тот же)
  
# Настройки синхронизации
sync:
  # Формат сообщений из Minecraft в Telegram
  mc-to-tg-format: "🎮 <player>: <message>"
  mc-to-tg-question-format: "❓ <player>: <message>"
  
  # Формат сообщений из Telegram в Minecraft  
  tg-to-mc-format: "§9[TG] §f<user>: §7<message>"
  tg-to-mc-question-format: "§6[TG-Вопрос] §f<user>: §7<message>"
  
  # Фильтрация сообщений
  filter:
    # Игнорировать сообщения без знаков препинания (? ! .)
    ignore-no-punctuation: true
    
    # Минимальная длина сообщения для отправки
    min-length: 3
    
    # Игнорировать команды в Minecraft
    ignore-commands: true
  
  # Разрешенные команды для синхронизации
  allowed-commands:
    - "!tg"
    - "!telegram"
  
  # Префикс для команд из Telegram в Minecraft
  tg-command-prefix: "!"

# Настройки вебхука для получения сообщений из Telegram
webhook:
  enabled: false  # Пока отключим - сложная настройка
  url: ""
  port: 8443
  secret-token: ""

# Настройки Long Polling (проще в настройке)
long-polling:
  enabled: true
  update-interval: 3  # секунды между проверками
